// Generated by gencpp from file track/TargetRobotArray.msg
// DO NOT EDIT!


#ifndef TRACK_MESSAGE_TARGETROBOTARRAY_H
#define TRACK_MESSAGE_TARGETROBOTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <track/TargetRobot.h>

namespace track
{
template <class ContainerAllocator>
struct TargetRobotArray_
{
  typedef TargetRobotArray_<ContainerAllocator> Type;

  TargetRobotArray_()
    : targets()  {
    }
  TargetRobotArray_(const ContainerAllocator& _alloc)
    : targets(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::track::TargetRobot_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::track::TargetRobot_<ContainerAllocator> >::other >  _targets_type;
  _targets_type targets;




  typedef boost::shared_ptr< ::track::TargetRobotArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::track::TargetRobotArray_<ContainerAllocator> const> ConstPtr;

}; // struct TargetRobotArray_

typedef ::track::TargetRobotArray_<std::allocator<void> > TargetRobotArray;

typedef boost::shared_ptr< ::track::TargetRobotArray > TargetRobotArrayPtr;
typedef boost::shared_ptr< ::track::TargetRobotArray const> TargetRobotArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::track::TargetRobotArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::track::TargetRobotArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace track

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'track': ['/home/olstob/track_ws/src/track/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::track::TargetRobotArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::track::TargetRobotArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::track::TargetRobotArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::track::TargetRobotArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::track::TargetRobotArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::track::TargetRobotArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::track::TargetRobotArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16223dc36cab66b58072ed5eb65e7309";
  }

  static const char* value(const ::track::TargetRobotArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16223dc36cab66b5ULL;
  static const uint64_t static_value2 = 0x8072ed5eb65e7309ULL;
};

template<class ContainerAllocator>
struct DataType< ::track::TargetRobotArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "track/TargetRobotArray";
  }

  static const char* value(const ::track::TargetRobotArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::track::TargetRobotArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TargetRobot[] targets\n\
================================================================================\n\
MSG: track/TargetRobot\n\
uint8 id\n\
uint8 color\n\
geometry_msgs/PoseStamped poseOrigin\n\
geometry_msgs/PoseStamped poseFcu\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::track::TargetRobotArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::track::TargetRobotArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetRobotArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::track::TargetRobotArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::track::TargetRobotArray_<ContainerAllocator>& v)
  {
    s << indent << "targets[]" << std::endl;
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      s << indent << "  targets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::track::TargetRobot_<ContainerAllocator> >::stream(s, indent + "    ", v.targets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACK_MESSAGE_TARGETROBOTARRAY_H
